        go mod download github.com/coreos/go-semver
        go mod download github.com/coreos/go-systemd
        go mod download github.com/coreos/pkg
        go mod download github.com/davecgh/go-spew
        go mod download github.com/fsnotify/fsnotify
        go mod download github.com/go-resty/resty/v2
        go mod download github.com/gogo/protobuf
        go mod download github.com/golang/protobuf
        go mod download github.com/golang/protobuf
        go mod download github.com/golang/protobuf
        go mod download github.com/golang/protobuf
        go mod download github.com/golang/protobuf
        go mod download github.com/golang/protobuf
        go mod download github.com/golang/protobuf
        go mod download github.com/google/uuid
        go mod download github.com/grpc-ecosystem/go-grpc-prometheus
        go mod download github.com/jinzhu/gorm
        go mod download github.com/jinzhu/gorm
        go mod download github.com/json-iterator/go
        go mod download github.com/labstack/echo/v4
        go mod download github.com/mitchellh/mapstructure
        go mod download github.com/modern-go/reflect2
        go mod download github.com/opentracing/opentracing-go
        go mod download github.com/opentracing/opentracing-go
        go mod download github.com/opentracing/opentracing-go
        go mod download github.com/pkg/errors
        go mod download github.com/prometheus/client_model
        go mod download github.com/prometheus/common
        go mod download github.com/prometheus/common
        go mod download github.com/prometheus/procfs
